package ejemplo03.dominio;
// Generated 19-feb-2019 10:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coche generated by hbm2java
 */
public class Coche  implements java.io.Serializable {


     private Integer idCoche;
     private int precio;
     private String marca;
     private String modelo;
     private String puertas;
     private Set<Motor> motors = new HashSet<Motor>(0);

    public Coche() {
    }

	
    public Coche(int precio, String marca, String modelo, String puertas) {
        this.precio = precio;
        this.marca = marca;
        this.modelo = modelo;
        this.puertas = puertas;
    }
    public Coche(int precio, String marca, String modelo, String puertas, Set<Motor> motors) {
       this.precio = precio;
       this.marca = marca;
       this.modelo = modelo;
       this.puertas = puertas;
       this.motors = motors;
    }
   
    public Integer getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(Integer idCoche) {
        this.idCoche = idCoche;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getPuertas() {
        return this.puertas;
    }
    
    public void setPuertas(String puertas) {
        this.puertas = puertas;
    }
    public Set<Motor> getMotors() {
        return this.motors;
    }
    
    public void setMotors(Set<Motor> motors) {
        this.motors = motors;
    }




}


