package ejemplo03.dominio;
// Generated 19-feb-2019 10:14:15 by Hibernate Tools 4.3.1



/**
 * Motor generated by hbm2java
 */
public class Motor  implements java.io.Serializable {


     private Integer idMotor;
     private Coche coche;
     private String combustible;
     private String potencia;

    public Motor() {
    }

    public Motor(Coche coche, String combustible, String potencia) {
       this.coche = coche;
       this.combustible = combustible;
       this.potencia = potencia;
    }
   
    public Integer getIdMotor() {
        return this.idMotor;
    }
    
    public void setIdMotor(Integer idMotor) {
        this.idMotor = idMotor;
    }
    public Coche getCoche() {
        return this.coche;
    }
    
    public void setCoche(Coche coche) {
        this.coche = coche;
    }
    public String getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(String combustible) {
        this.combustible = combustible;
    }
    public String getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(String potencia) {
        this.potencia = potencia;
    }




}


